version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: mini-proj
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - '.:/usr/usr/appl'
    command: sleep infinity
    depends_on:
      - postgres
    networks:
      - be
      - localstack_default

  postgres:
    container_name: postgres-mini-proj
    hostname: postgres
    image: postgres:13
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=mini_db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
      - DIALECT=postgres
    volumes:
      - postgres_volume:/var/lib/postgres/data
    networks:
      - be
      - localstack_default
  
  # mongodb:

volumes:
  postgres_volume: {}
  # mongodb_volume: {}

networks:
  localstack_default:
    external: true
  be:
